/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   test_ft_isdigit.c                                  :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: eduribei <eduribei@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/04/23 18:22:00 by eduribei          #+#    #+#             */
/*   Updated: 2024/04/29 18:51:10 by eduribei         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "tester.h"

int ft_isdigit(int c);

typedef struct
{
    int input;
    char *comment;
} Test;


typedef struct failed_test_node
{
    Test test;
    struct failed_test_node *next;
} FailedTestNode;

// Function to execute and print test results
void run_test(Test test, FailedTestNode **failed_tests, int *fail_count)
{
    int expected = isdigit(test.input);
    int result = ft_isdigit(test.input);

    if ((result == 0) && (expected == 0))
    {
        printf(COLOR_GREEN "%d " COLOR_RESET, test.input);
    }
    else if ((result != 0) && (expected != 0))
    {
        printf(COLOR_GREEN "%d " COLOR_RESET, test.input);
    }
    else
    {
        printf(COLOR_RED "(%d) " COLOR_RESET, test.input);
        FailedTestNode *new_node = malloc(sizeof(FailedTestNode));
        new_node->test = test; // the test that failed
        new_node->next = *failed_tests;
        *failed_tests = new_node;
        (*fail_count)++;
    }
}

#define NUM_TESTS 512

int main(void)
{
    int fail_counter = 0;

	FailedTestNode *failed_tests = NULL;

    Test tests[NUM_TESTS] = {
        {0, "NULL character (ASCII)"},
        {1, "Start of Heading (ASCII)"},
        {2, "Start of Text (ASCII)"},
        {3, "End of Text (ASCII)"},
        {4, "End of Transmission (ASCII)"},
        {5, "Enquiry (ASCII)"},
        {6, "Acknowledge (ASCII)"},
        {7, "Bell (ASCII)"},
        {8, "Backspace (ASCII)"},
        {9, "Horizontal Tab (ASCII)"},
        {10, "Line Feed (ASCII)"},
        {11, "Vertical Tab (ASCII)"},
        {12, "Form Feed (ASCII)"},
        {13, "Carriage Return (ASCII)"},
        {14, "Shift Out (ASCII)"},
        {15, "Shift In (ASCII)"},
        {16, "Data Link Escape (ASCII)"},
        {17, "Device Control 1 (ASCII)"},
        {18, "Device Control 2 (ASCII)"},
        {19, "Device Control 3 (ASCII)"},
        {20, "Device Control 4 (ASCII)"},
        {21, "Negative Acknowledge (ASCII)"},
        {22, "Synchronous Idle (ASCII)"},
        {23, "End of Transmission Block (ASCII)"},
        {24, "Cancel (ASCII)"},
        {25, "End of Medium (ASCII)"},
        {26, "Substitute (ASCII)"},
        {27, "Escape (ASCII)"},
        {28, "File Separator (ASCII)"},
        {29, "Group Separator (ASCII)"},
        {30, "Record Separator (ASCII)"},
        {31, "Unit Separator (ASCII)"},
        {32, "Space (ASCII)"},
        {33, "Exclamation Mark (ASCII)"},
        {34, "Double Quote (ASCII)"},
        {35, "Number Sign (ASCII)"},
        {36, "Dollar Sign (ASCII)"},
        {37, "Percent Sign (ASCII)"},
        {38, "Ampersand (ASCII)"},
        {39, "Single Quote (ASCII)"},
        {40, "Left Parenthesis (ASCII)"},
        {41, "Right Parenthesis (ASCII)"},
        {42, "Asterisk (ASCII)"},
        {43, "Plus Sign (ASCII)"},
        {44, "Comma (ASCII)"},
        {45, "Hyphen-Minus (ASCII)"},
        {46, "Full Stop (ASCII)"},
        {47, "Slash (ASCII)"},
        {48, "Digit 0 (ASCII)"},
        {49, "Digit 1 (ASCII)"},
        {50, "Digit 2 (ASCII)"},
        {51, "Digit 3 (ASCII)"},
        {52, "Digit 4 (ASCII)"},
        {53, "Digit 5 (ASCII)"},
        {54, "Digit 6 (ASCII)"},
        {55, "Digit 7 (ASCII)"},
        {56, "Digit 8 (ASCII)"},
        {57, "Digit 9 (ASCII)"},
        {58, "Colon (ASCII)"},
        {59, "Semicolon (ASCII)"},
        {60, "Less Than Sign (ASCII)"},
        {61, "Equals Sign (ASCII)"},
        {62, "Greater Than Sign (ASCII)"},
        {63, "Question Mark (ASCII)"},
        {64, "At Sign (ASCII)"},
        {65, "Uppercase Letter A (ASCII)"},
        {66, "Uppercase Letter B (ASCII)"},
        {67, "Uppercase Letter C (ASCII)"},
        {68, "Uppercase Letter D (ASCII)"},
        {69, "Uppercase Letter E (ASCII)"},
        {70, "Uppercase Letter F (ASCII)"},
        {71, "Uppercase Letter G (ASCII)"},
        {72, "Uppercase Letter H (ASCII)"},
        {73, "Uppercase Letter I (ASCII)"},
        {74, "Uppercase Letter J (ASCII)"},
        {75, "Uppercase Letter K (ASCII)"},
        {76, "Uppercase Letter L (ASCII)"},
        {77, "Uppercase Letter M (ASCII)"},
        {78, "Uppercase Letter N (ASCII)"},
        {79, "Uppercase Letter O (ASCII)"},
        {80, "Uppercase Letter P (ASCII)"},
        {81, "Uppercase Letter Q (ASCII)"},
        {82, "Uppercase Letter R (ASCII)"},
        {83, "Uppercase Letter S (ASCII)"},
        {84, "Uppercase Letter T (ASCII)"},
        {85, "Uppercase Letter U (ASCII)"},
        {86, "Uppercase Letter V (ASCII)"},
        {87, "Uppercase Letter W (ASCII)"},
        {88, "Uppercase Letter X (ASCII)"},
        {89, "Uppercase Letter Y (ASCII)"},
        {90, "Uppercase Letter Z (ASCII)"},
        {91, "Left Square Bracket (ASCII)"},
        {92, "Backslash (ASCII)"},
        {93, "Right Square Bracket (ASCII)"},
        {94, "Circumflex Accent (ASCII)"},
        {95, "Underscore (ASCII)"},
        {96, "Grave Accent (ASCII)"},
        {97, "Lowercase Letter a (ASCII)"},
        {98, "Lowercase Letter b (ASCII)"},
        {99, "Lowercase Letter c (ASCII)"},
        {100, "Lowercase Letter d (ASCII)"},
        {101, "Lowercase Letter e (ASCII)"},
        {102, "Lowercase Letter f (ASCII)"},
        {103, "Lowercase Letter g (ASCII)"},
        {104, "Lowercase Letter h (ASCII)"},
        {105, "Lowercase Letter i (ASCII)"},
        {106, "Lowercase Letter j (ASCII)"},
        {107, "Lowercase Letter k (ASCII)"},
        {108, "Lowercase Letter l (ASCII)"},
        {109, "Lowercase Letter m (ASCII)"},
        {110, "Lowercase Letter n (ASCII)"},
        {111, "Lowercase Letter o (ASCII)"},
        {112, "Lowercase Letter p (ASCII)"},
        {113, "Lowercase Letter q (ASCII)"},
        {114, "Lowercase Letter r (ASCII)"},
        {115, "Lowercase Letter s (ASCII)"},
        {116, "Lowercase Letter t (ASCII)"},
        {117, "Lowercase Letter u (ASCII)"},
        {118, "Lowercase Letter v (ASCII)"},
        {119, "Lowercase Letter w (ASCII)"},
        {120, "Lowercase Letter x (ASCII)"},
        {121, "Lowercase Letter y (ASCII)"},
        {122, "Lowercase Letter z (ASCII)"},
        {123, "Left Curly Bracket (ASCII)"},
        {124, "Vertical Bar (ASCII)"},
        {125, "Right Curly Bracket (ASCII)"},
        {126, "Tilde (ASCII)"},
        {127, "Delete (ASCII)"},
        // Extended ASCII
        {128, "Ç (Latin Capital Letter C With Cedilla)"},
        {129, "ü (Latin Small Letter U With Diaeresis)"},
        {130, "é (Latin Small Letter E With Acute)"},
        {131, "â (Latin Small Letter A With Circumflex)"},
        {132, "ä (Latin Small Letter A With Diaeresis)"},
        {133, "à (Latin Small Letter A With Grave)"},
        {134, "å (Latin Small Letter A With Ring Above)"},
        {135, "ç (Latin Small Letter C With Cedilla)"},
        {136, "ê (Latin Small Letter E With Circumflex)"},
        {137, "ë (Latin Small Letter E With Diaeresis)"},
        {138, "è (Latin Small Letter E With Grave)"},
        {139, "ï (Latin Small Letter I With Diaeresis)"},
        {140, "î (Latin Small Letter I With Circumflex)"},
        {141, "ì (Latin Small Letter I With Grave)"},
        {142, "Ä (Latin Capital Letter A With Diaeresis)"},
        {143, "Å (Latin Capital Letter A With Ring Above)"},
        {144, "É (Latin Capital Letter E With Acute)"},
        {145, "æ (Latin Small Letter Ae)"},
        {146, "Æ (Latin Capital Letter Ae)"},
        {147, "ô (Latin Small Letter O With Circumflex)"},
        {148, "ö (Latin Small Letter O With Diaeresis)"},
        {149, "ò (Latin Small Letter O With Grave)"},
        {150, "û (Latin Small Letter U With Circumflex)"},
        {151, "ù (Latin Small Letter U With Grave)"},
        {152, "ÿ (Latin Small Letter Y With Diaeresis)"},
        {153, "Ö (Latin Capital Letter O With Diaeresis)"},
        {154, "Ü (Latin Capital Letter U With Diaeresis)"},
        {155, "ø (Latin Small Letter O With Stroke)"},
        {156, "£ (Pound Sign)"},
        {157, "Ø (Latin Capital Letter O With Stroke)"},
        {158, "× (Multiplication Sign)"},
        {159, "ƒ (Latin Small Letter F With Hook)"},
        {160, "á (Latin Small Letter A With Acute)"},
        {161, "í (Latin Small Letter I With Acute)"},
        {162, "ó (Latin Small Letter O With Acute)"},
        {163, "ú (Latin Small Letter U With Acute)"},
        {164, "ñ (Latin Small Letter N With Tilde)"},
        {165, "Ñ (Latin Capital Letter N With Tilde)"},
        {166, "ª (Feminine Ordinal Indicator)"},
        {167, "º (Masculine Ordinal Indicator)"},
        {168, "¿ (Inverted Question Mark)"},
        {169, "⌐ (Reversed Not Sign)"},
        {170, "¬ (Not Sign)"},
        {171, "½ (Vulgar Fraction One Half)"},
        {172, "¼ (Vulgar Fraction One Quarter)"},
        {173, "¡ (Inverted Exclamation Mark)"},
        {174, "« (Left-Pointing Double Angle Quotation Mark)"},
        {175, "» (Right-Pointing Double Angle Quotation Mark)"},
        {176, "░ (Light Shade)"},
        {177, "▒ (Medium Shade)"},
        {178, "▓ (Dark Shade)"},
        {179, "│ (Box Drawings Light Vertical)"},
        {180, "┤ (Box Drawings Light Vertical And Left)"},
        {181, "Á (Latin Capital Letter A With Acute)"},
        {182, "Â (Latin Capital Letter A With Circumflex)"},
        {183, "À (Latin Capital Letter A With Grave)"},
        {184, "© (Copyright Sign)"},
        {185, "╣ (Box Drawings Double Vertical And Left)"},
        {186, "║ (Box Drawings Double Vertical)"},
        {187, "╗ (Box Drawings Double Down And Left)"},
        {188, "╝ (Box Drawings Double Up And Left)"},
        {189, "¢ (Cent Sign)"},
        {190, "¥ (Yen Sign)"},
        {191, "┐ (Box Drawings Light Down And Left)"},
        {192, "└ (Box Drawings Light Up And Right)"},
        {193, "┴ (Box Drawings Light Up And Horizontal)"},
        {194, "┬ (Box Drawings Light Down And Horizontal)"},
        {195, "├ (Box Drawings Light Vertical And Right)"},
        {196, "─ (Box Drawings Light Horizontal)"},
        {197, "┼ (Box Drawings Light Vertical And Horizontal)"},
        {198, "ã (Latin Small Letter A With Tilde)"},
        {199, "Ã (Latin Capital Letter A With Tilde)"},
        {200, "╚ (Box Drawings Double Up And Right)"},
        {201, "╔ (Box Drawings Double Down And Right)"},
        {202, "╩ (Box Drawings Double Up And Horizontal)"},
        {203, "╦ (Box Drawings Double Down And Horizontal)"},
        {204, "╠ (Box Drawings Double Vertical And Right)"},
        {205, "═ (Box Drawings Double Horizontal)"},
        {206, "╬ (Box Drawings Double Vertical And Horizontal)"},
        {207, "¤ (Currency Sign)"},
        {208, "ð (Latin Small Letter Eth)"},
        {209, "Ð (Latin Capital Letter Eth)"},
        {210, "Ê (Latin Capital Letter E With Circumflex)"},
        {211, "Ë (Latin Capital Letter E With Diaeresis)"},
        {212, "È (Latin Capital Letter E With Grave)"},
        {213, "ı (Latin Small Letter Dotless I)"},
        {214, "Í (Latin Capital Letter I With Acute)"},
        {215, "Î (Latin Capital Letter I With Circumflex)"},
        {216, "Ï (Latin Capital Letter I With Diaeresis)"},
        {217, "┘ (Box Drawings Light Up And Left)"},
        {218, "┌ (Box Drawings Light Down And Right)"},
        {219, "█ (Full Block)"},
        {220, "▄ (Lower Half Block)"},
        {221, "¦ (Broken Bar)"},
        {222, "Ì (Latin Capital Letter I With Grave)"},
        {223, "▀ (Upper Half Block)"},
        {224, "Ó (Latin Capital Letter O With Acute)"},
        {225, "ß (Latin Small Letter Sharp S)"},
        {226, "Ô (Latin Capital Letter O With Circumflex)"},
        {227, "Ò (Latin Capital Letter O With Grave)"},
        {228, "õ (Latin Small Letter O With Tilde)"},
        {229, "Õ (Latin Capital Letter O With Tilde)"},
        {230, "µ (Micro Sign)"},
        {231, "þ (Latin Small Letter Thorn)"},
        {232, "Þ (Latin Capital Letter Thorn)"},
        {233, "Ú (Latin Capital Letter U With Acute)"},
        {234, "Û (Latin Capital Letter U With Circumflex)"},
        {235, "Ù (Latin Capital Letter U With Grave)"},
        {236, "ý (Latin Small Letter Y With Acute)"},
        {237, "Ý (Latin Capital Letter Y With Acute)"},
        {238, "¯ (Macron)"},
        {239, "´ (Acute Accent)"},
        {240, "≡ (Congruence Sign)"},
        {241, "± (Plus-Minus Sign)"},
        {242, "‗ (Double Low Line)"},
        {243, "¾ (Vulgar Fraction Three Quarters)"},
        {244, "¶ (Pilcrow Sign)"},
        {245, "§ (Section Sign)"},
        {246, "÷ (Division Sign)"},
        {247, "¸ (Cedilla)"},
        {248, "° (Degree Sign)"},
        {249, "¨ (Diaeresis)"},
        {250, "· (Middle Dot)"},
        {251, "¹ (Superscript One)"},
        {252, "³ (Superscript Three)"},
        {253, "² (Superscript Two)"},
        {254, "■ (Black Square)"},
        {255, "nbsp (Non-Breaking Space)"},
        // // Additional Unicode characters
            {256, "¡ (Inverted Exclamation Mark)"},
    {257, "¢ (Cent Sign)"},
    {258, "£ (Pound Sign)"},
    {259, "¤ (Currency Sign)"},
    {260, "¥ (Yen Sign)"},
    {261, "¦ (Broken Vertical Bar)"},
    {262, "§ (Section Sign)"},
    {263, "¨ (Diaeresis)"},
    {264, "© (Copyright Sign)"},
    {265, "ª (Feminine Ordinal Indicator)"},
    {266, "« (Left-Pointing Double Angle Quotation Mark)"},
    {267, "¬ (Not Sign)"},
    {268, "­ (Soft Hyphen)"},
    {269, "® (Registered Sign)"},
    {270, "¯ (Macron)"},
    {271, "° (Degree Sign)"},
    {272, "± (Plus-Minus Sign)"},
    {273, "² (Superscript Two)"},
    {274, "³ (Superscript Three)"},
    {275, "´ (Acute Accent)"},
    {276, "µ (Micro Sign)"},
    {277, "¶ (Pilcrow Sign)"},
    {278, "· (Middle Dot)"},
    {279, "¸ (Cedilla)"},
    {280, "¹ (Superscript One)"},
    {281, "º (Masculine Ordinal Indicator)"},
    {282, "» (Right-Pointing Double Angle Quotation Mark)"},
    {283, "¼ (Vulgar Fraction One Quarter)"},
    {284, "½ (Vulgar Fraction One Half)"},
    {285, "¾ (Vulgar Fraction Three Quarters)"},
    {286, "¿ (Inverted Question Mark)"},
    {287, "À (Latin Capital Letter A With Grave)"},
    {288, "Á (Latin Capital Letter A With Acute)"},
    {289, "Â (Latin Capital Letter A With Circumflex)"},
    {290, "Ã (Latin Capital Letter A With Tilde)"},
    {291, "Ä (Latin Capital Letter A With Diaeresis)"},
    {292, "Å (Latin Capital Letter A With Ring Above)"},
    {293, "Æ (Latin Capital Letter AE)"},
    {294, "Ç (Latin Capital Letter C With Cedilla)"},
    {295, "È (Latin Capital Letter E With Grave)"},
    {296, "É (Latin Capital Letter E With Acute)"},
    {297, "Ê (Latin Capital Letter E With Circumflex)"},
    {298, "Ë (Latin Capital Letter E With Diaeresis)"},
    {299, "Ì (Latin Capital Letter I With Grave)"},
    {300, "Í (Latin Capital Letter I With Acute)"},
    {301, "Î (Latin Capital Letter I With Circumflex)"},
    {302, "Ï (Latin Capital Letter I With Diaeresis)"},
    {303, "Ð (Latin Capital Letter Eth)"},
    {304, "Ñ (Latin Capital Letter N With Tilde)"},
    {305, "Ò (Latin Capital Letter O With Grave)"},
    {306, "Ó (Latin Capital Letter O With Acute)"},
    {307, "Ô (Latin Capital Letter O With Circumflex)"},
    {308, "Õ (Latin Capital Letter O With Tilde)"},
    {309, "Ö (Latin Capital Letter O With Diaeresis)"},
    {310, "× (Multiplication Sign)"},
    {311, "Ø (Latin Capital Letter O With Stroke)"},
    {312, "Ù (Latin Capital Letter U With Grave)"},
    {313, "Ú (Latin Capital Letter U With Acute)"},
    {314, "Û (Latin Capital Letter U With Circumflex)"},
    {315, "Ü (Latin Capital Letter U With Diaeresis)"},
    {316, "Ý (Latin Capital Letter Y With Acute)"},
    {317, "Þ (Latin Capital Letter Thorn)"},
    {318, "ß (Latin Small Letter Sharp S)"},
    {319, "à (Latin Small Letter A With Grave)"},
    {320, "á (Latin Small Letter A With Acute)"},
    {321, "â (Latin Small Letter A With Circumflex)"},
    {322, "ã (Latin Small Letter A With Tilde)"},
    {323, "ä (Latin Small Letter A With Diaeresis)"},
    {324, "å (Latin Small Letter A With Ring Above)"},
    {325, "æ (Latin Small Letter AE)"},
    {326, "ç (Latin Small Letter C With Cedilla)"},
    {327, "è (Latin Small Letter E With Grave)"},
    {328, "é (Latin Small Letter E With Acute)"},
    {329, "ê (Latin Small Letter E With Circumflex)"},
    {330, "ë (Latin Small Letter E With Diaeresis)"},
    {331, "ì (Latin Small Letter I With Grave)"},
    {332, "í (Latin Small Letter I With Acute)"},
    {333, "î (Latin Small Letter I With Circumflex)"},
    {334, "ï (Latin Small Letter I With Diaeresis)"},
    {335, "ð (Latin Small Letter Eth)"},
    {336, "ñ (Latin Small Letter N With Tilde)"},
    {337, "ò (Latin Small Letter O With Grave)"},
    {338, "ó (Latin Small Letter O With Acute)"},
    {339, "ô (Latin Small Letter O With Circumflex)"},
    {340, "õ (Latin Small Letter O With Tilde)"},
    {341, "ö (Latin Small Letter O With Diaeresis)"},
    {342, "÷ (Division Sign)"},
    {343, "ø (Latin Small Letter O With Stroke)"},
    {344, "ù (Latin Small Letter U With Grave)"},
    {345, "ú (Latin Small Letter U With Acute)"},
    {346, "û (Latin Small Letter U With Circumflex)"},
    {347, "ü (Latin Small Letter U With Diaeresis)"},
    {348, "ý (Latin Small Letter Y With Acute)"},
    {349, "þ (Latin Small Letter Thorn)"},
    {350, "ÿ (Latin Small Letter Y With Diaeresis)"},
    {351, "Ā (Latin Capital Letter A With Macron)"},
    {352, "ā (Latin Small Letter A With Macron)"},
    {353, "Ă (Latin Capital Letter A With Breve)"},
    {354, "ă (Latin Small Letter A With Breve)"},
    {355, "Ą (Latin Capital Letter A With Ogonek)"},
    {356, "ą (Latin Small Letter A With Ogonek)"},
    {357, "Ć (Latin Capital Letter C With Acute)"},
    {358, "ć (Latin Small Letter C With Acute)"},
    {359, "Ĉ (Latin Capital Letter C With Circumflex)"},
    {360, "ĉ (Latin Small Letter C With Circumflex)"},
    {361, "Ċ (Latin Capital Letter C With Dot Above)"},
    {362, "ċ (Latin Small Letter C With Dot Above)"},
    {363, "Č (Latin Capital Letter C With Caron)"},
    {364, "č (Latin Small Letter C With Caron)"},
    {365, "Ď (Latin Capital Letter D With Caron)"},
    {366, "ď (Latin Small Letter D With Caron)"},
    {367, "Đ (Latin Capital Letter D With Stroke)"},
    {368, "đ (Latin Small Letter D With Stroke)"},
    {369, "Ē (Latin Capital Letter E With Macron)"},
    {370, "ē (Latin Small Letter E With Macron)"},
    {371, "Ĕ (Latin Capital Letter E With Breve)"},
    {372, "ĕ (Latin Small Letter E With Breve)"},
    {373, "Ė (Latin Capital Letter E With Dot Above)"},
    {374, "ė (Latin Small Letter E With Dot Above)"},
    {375, "Ę (Latin Capital Letter E With Ogonek)"},
    {376, "ę (Latin Small Letter E With Ogonek)"},
    {377, "Ě (Latin Capital Letter E With Caron)"},
    {378, "ě (Latin Small Letter E With Caron)"},
    {379, "Ĝ (Latin Capital Letter G With Circumflex)"},
    {380, "ĝ (Latin Small Letter G With Circumflex)"},
    {381, "Ğ (Latin Capital Letter G With Breve)"},
    {382, "ğ (Latin Small Letter G With Breve)"},
    {383, "Ġ (Latin Capital Letter G With Dot Above)"},
    {384, "ġ (Latin Small Letter G With Dot Above)"},
    {385, "Ģ (Latin Capital Letter G With Cedilla)"},
    {386, "ģ (Latin Small Letter G With Cedilla)"},
    {387, "Ĥ (Latin Capital Letter H With Circumflex)"},
    {388, "ĥ (Latin Small Letter H With Circumflex)"},
    {389, "Ħ (Latin Capital Letter H With Stroke)"},
    {390, "ħ (Latin Small Letter H With Stroke)"},
    {391, "Ĩ (Latin Capital Letter I With Tilde)"},
    {392, "ĩ (Latin Small Letter I With Tilde)"},
    {393, "Ī (Latin Capital Letter I With Macron)"},
    {394, "ī (Latin Small Letter I With Macron)"},
    {395, "Ĭ (Latin Capital Letter I With Breve)"},
    {396, "ĭ (Latin Small Letter I With Breve)"},
    {397, "Į (Latin Capital Letter I With Ogonek)"},
    {398, "į (Latin Small Letter I With Ogonek)"},
    {399, "İ (Latin Capital Letter I With Dot Above)"},
    {400, "ı (Latin Small Letter Dotless I)"},
    {401, "Ĳ (Latin Capital Ligature IJ)"},
    {402, "ĳ (Latin Small Ligature IJ)"},
    {403, "Ĵ (Latin Capital Letter J With Circumflex)"},
    {404, "ĵ (Latin Small Letter J With Circumflex)"},
    {405, "Ķ (Latin Capital Letter K With Cedilla)"},
    {406, "ķ (Latin Small Letter K With Cedilla)"},
    {407, "ĸ (Latin Small Letter Kra)"},
    {408, "Ĺ (Latin Capital Letter L With Acute)"},
    {409, "ĺ (Latin Small Letter L With Acute)"},
    {410, "Ļ (Latin Capital Letter L With Cedilla)"},
    {411, "ļ (Latin Small Letter L With Cedilla)"},
    {412, "Ľ (Latin Capital Letter L With Caron)"},
    {413, "ľ (Latin Small Letter L With Caron)"},
    {414, "Ŀ (Latin Capital Letter L With Middle Dot)"},
    {415, "ŀ (Latin Small Letter L With Middle Dot)"},
    {416, "Ł (Latin Capital Letter L With Stroke)"},
    {417, "ł (Latin Small Letter L With Stroke)"},
    {418, "Ń (Latin Capital Letter N With Acute)"},
    {419, "ń (Latin Small Letter N With Acute)"},
    {420, "Ņ (Latin Capital Letter N With Cedilla)"},
    {421, "ņ (Latin Small Letter N With Cedilla)"},
    {422, "Ň (Latin Capital Letter N With Caron)"},
    {423, "ň (Latin Small Letter N With Caron)"},
    {424, "ŉ (Latin Small Letter N Preceded By Apostrophe)"},
    {425, "Ŋ (Latin Capital Letter Eng)"},
    {426, "ŋ (Latin Small Letter Eng)"},
    {427, "Ō (Latin Capital Letter O With Macron)"},
    {428, "ō (Latin Small Letter O With Macron)"},
    {429, "Ŏ (Latin Capital Letter O With Breve)"},
    {430, "ŏ (Latin Small Letter O With Breve)"},
    {431, "Ő (Latin Capital Letter O With Double Acute)"},
    {432, "ő (Latin Small Letter O With Double Acute)"},
    {433, "Œ (Latin Capital Ligature OE)"},
    {434, "œ (Latin Small Ligature OE)"},
    {435, "Ŕ (Latin Capital Letter R With Acute)"},
    {436, "ŕ (Latin Small Letter R With Acute)"},
    {437, "Ŗ (Latin Capital Letter R With Cedilla)"},
    {438, "ŗ (Latin Small Letter R With Cedilla)"},
    {439, "Ř (Latin Capital Letter R With Caron)"},
    {440, "ř (Latin Small Letter R With Caron)"},
    {441, "Ś (Latin Capital Letter S With Acute)"},
    {442, "ś (Latin Small Letter S With Acute)"},
    {443, "Ŝ (Latin Capital Letter S With Circumflex)"},
    {444, "ŝ (Latin Small Letter S With Circumflex)"},
    {445, "Ş (Latin Capital Letter S With Cedilla)"},
    {446, "ş (Latin Small Letter S With Cedilla)"},
    {447, "Š (Latin Capital Letter S With Caron)"},
    {448, "š (Latin Small Letter S With Caron)"},
    {449, "Ţ (Latin Capital Letter T With Cedilla)"},
    {450, "ţ (Latin Small Letter T With Cedilla)"},
    {451, "Ť (Latin Capital Letter T With Caron)"},
    {452, "ť (Latin Small Letter T With Caron)"},
    {453, "Ŧ (Latin Capital Letter T With Stroke)"},
    {454, "ŧ (Latin Small Letter T With Stroke)"},
    {455, "Ũ (Latin Capital Letter U With Tilde)"},
    {456, "ũ (Latin Small Letter U With Tilde)"},
    {457, "Ū (Latin Capital Letter U With Macron)"},
    {458, "ū (Latin Small Letter U With Macron)"},
    {459, "Ŭ (Latin Capital Letter U With Breve)"},
    {460, "ŭ (Latin Small Letter U With Breve)"},
    {461, "Ů (Latin Capital Letter U With Ring Above)"},
    {462, "ů (Latin Small Letter U With Ring Above)"},
    {463, "Ű (Latin Capital Letter U With Double Acute)"},
    {464, "ű (Latin Small Letter U With Double Acute)"},
    {465, "Ų (Latin Capital Letter U With Ogonek)"},
    {466, "ų (Latin Small Letter U With Ogonek)"},
    {467, "Ŵ (Latin Capital Letter W With Circumflex)"},
    {468, "ŵ (Latin Small Letter W With Circumflex)"},
    {469, "Ŷ (Latin Capital Letter Y With Circumflex)"},
    {470, "ŷ (Latin Small Letter Y With Circumflex)"},
    {471, "Ÿ (Latin Capital Letter Y With Diaeresis)"},
    {472, "Ź (Latin Capital Letter Z With Acute)"},
    {473, "ź (Latin Small Letter Z With Acute)"},
    {474, "Ż (Latin Capital Letter Z With Dot Above)"},
    {475, "ż (Latin Small Letter Z With Dot Above)"},
    {476, "Ž (Latin Capital Letter Z With Caron)"},
    {477, "ž (Latin Small Letter Z With Caron)"},
    {478, "ſ (Latin Small Letter Long S)"},
    {479, "ƀ (Latin Small Letter B With Stroke)"},
    {480, "Ɓ (Latin Capital Letter B With Hook)"},
    {481, "Ƃ (Latin Capital Letter B With Topbar)"},
    {482, "ƃ (Latin Small Letter B With Topbar)"},
    {483, "Ƅ (Latin Capital Letter Tone Six)"},
    {484, "ƅ (Latin Small Letter Tone Six)"},
    {485, "Ɔ (Latin Capital Letter Open O)"},
    {486, "Ƈ (Latin Capital Letter C With Hook)"},
    {487, "ƈ (Latin Small Letter C With Hook)"},
    {488, "Ɖ (Latin Capital Letter African D)"},
    {489, "Ɗ (Latin Capital Letter D With Hook)"},
    {490, "Ƌ (Latin Capital Letter D With Topbar)"},
    {491, "ƌ (Latin Small Letter D With Topbar)"},
    {492, "ƍ (Latin Small Letter Turned Delta)"},
    {493, "Ǝ (Latin Capital Letter Reversed E)"},
    {494, "Ə (Latin Capital Letter Schwa)"},
    {495, "Ɛ (Latin Capital Letter Open E)"},
    {496, "Ƒ (Latin Capital Letter F With Hook)"},
    {497, "ƒ (Latin Small Letter F With Hook)"},
    {498, "Ɠ (Latin Capital Letter African G)"},
    {499, "Ɣ (Latin Capital Letter Gamma)"},
    {500, "ƕ (Latin Small Letter Hv)"},
    {501, "Ɩ (Latin Capital Letter Iota)"},
    {502, "Ɨ (Latin Capital Letter I With Stroke)"},
    {503, "Ƙ (Latin Capital Letter K With Hook)"},
    {504, "ƙ (Latin Small Letter K With Hook)"},
    {505, "ƚ (Latin Small Letter L With Bar)"},
    {506, "ƛ (Latin Small Letter Lambda With Stroke)"},
    {507, "Ɯ (Latin Capital Letter Turned M)"},
    {508, "Ɲ (Latin Capital Letter N With Left Hook)"},
    {509, "ƞ (Latin Small Letter N With Left Hook)"},
    {510, "Ɵ (Latin Capital Letter O With Middle Tilde)"},
    {511, "Ơ (Latin Capital Letter O With Horn)"}	
        // {0x1F600, "😀 (Grinning Face Emoji)"},  // Hex input for emoji
        // {0x1F601, "😁 (Grinning Face With Smiling Eyes Emoji)"},
        // {0x1F602, "😂 (Face With Tears of Joy Emoji)"},
        // {0x1F605, "😅 (Smiling Face With Open Mouth & Cold Sweat)"},
		// {0x1F609, "😉 (Winking Face)"},
		// {-1, "Negative One"},  // Negative integer
        // {-128, "Negative One Twenty-Eight"},
        // {-255, "Negative Two Fifty-Five"},
        // {0xFFFFFF, "Hex 0xFFFFFF"},  // Large hex input
        // {0xFFFFFFF, "Hex 0xFFFFFFF"}
		};


	printf(COLOR_BLUE ">TESTING ft_isdigit------------------------------------------------------------------------\n" COLOR_RESET);
    printf("Comparing ft_isdigit (result) with isdigit/ctype.h (expected).\n");

	printf("As long the expected and the result values are non-zero, it's a PASS.\n");

	// RUNNING TESTS
	for (int i = 0; i < NUM_TESTS; i++)
    run_test(tests[i], &failed_tests, &fail_counter);

	printf("\n\n");


	// SAVING RESULTS
    if (fail_counter > 0)
        ft_save_results("ft_isdigit: FAIL");
    else
        ft_save_results("ft_isdigit: OK");

    FailedTestNode *current = failed_tests;
    while (current != NULL)
    {
        printf(COLOR_RED "Failed: input = %d (%s) expected = %d | result = %d \n" COLOR_RESET, current->test.input, current->test.comment, isdigit(current->test.input), ft_isdigit(current->test.input));
        FailedTestNode *next = current->next;
        free(current);
        current = next;
    }


    printf("\n");
    return (0);
}
